name: class_whisperer
description: Classroom engagement (Courses + Lectures + Answers) using Firebase Realtime Database and Bloc.
publish_to: "none"
version: 2.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_database: ^11.1.2
  google_sign_in: ^6.2.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
